name: web_chrome_api
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.1.1 <4.0.0'
  
dependencies:
  meta: any
  js: any